Config.Vehicles = {
    {
        model = "taco",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "romero",
        category = "sedans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "emperor",
        category = "sedans",
        price = 8000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tornado5",
        category = "sedans",
        price = 7000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dloader",
        category = "suvs",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "broadway",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "btype2",
        category = "suvs",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hermes",
        category = "sedans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "pigalle",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "clique",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "clique2",
        category = "sedans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hustler",
        category = "suvs",
        price = 11000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "kalahari",
        category = "offroad",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "peyote",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stafford",
        category = "suvs",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "voodoo2",
        category = "sedans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "journey",
        category = "vans",
        price = 11000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "manana2",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "postlude",
        category = "sedans",
        price = 6500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "surfer",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "voodoo",
        category = "sedans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "washington",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "weevil",
        category = "sedans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tornado",
        category = "sedans",
        price = 7850,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tahoma",
        category = "sedans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "glendale2",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "fagaloa",
        category = "suvs",
        price = 10560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "lurcher",
        category = "sedans",
        price = 8560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
     {
        model = "dynasty",
        category = "sedans",
        price = 7850,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "regina",
        category = "sedans",
        price = 8540,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "glendale",
        category = "sedans",
        price = 7560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo",
        category = "sedans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "warrener",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "patriot",
        category = "suvs",
        price = 12000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "kanjosj",
        category = "sedans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "manana",
        category = "sedans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler5",
        category = "sedans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dukes3",
        category = "sedans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "eudora",
        category = "sedans",
        price = 6500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rancherxl",
        category = "suvs",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },    
    {
        model = "camper",
        category = "vans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "boxville",
        category = "vans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck3",
        category = "vans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck2",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck4",
        category = "vans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule3",
        category = "vans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule4",
        category = "vans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "primo",
        category = "sedans",
        price = 13000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "seminole",
        category = "suvs",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo2",
        category = "sedans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "monstrociti",
        category = "suvs",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "coquette2",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "coquette3",
        category = "sports",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "chino",
        category = "sedans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "chino2",
        category = "sedans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asbo",
        category = "sedans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bifta",
        category = "offroad",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bison",
        category = "vans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bodhi2",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "boor",
        category = "sedans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dilettante",
        category = "sedans",
        price = 12300,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler",
        category = "sedans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "primo2",
        category = "sedans",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stinger",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stanier",
        category = "sedans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "slamvan2",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tulip2",
        category = "sedans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hotknife",
        category = "sports",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo3",
        category = "sedans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
        {
        model = "granger",
        category = "suvs",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "greenwood",
        category = "sedans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "ztype",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mesa",
        category = "offroad",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "slamvan",
        category = "vans",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "seminole2",
        category = "suvs",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "landstalker2",
        category = "suvs",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "radi",
        category = "suvs",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "habanero",
        category = "suvs",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mesa3",
        category = "offroad",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "emperor2",
        category = "sedans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "faction2",
        category = "sedans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "btype3",
        category = "sedans",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bjxl",
        category = "suvs",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbvivant",
        category = "sports",
        price = 15500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "baller",
        category = "suvs",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asterope",
        category = "sedans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "panto",
        category = "compacts",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "ingot",
        category = "sedans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "lguard",
        category = "suvs",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "winky",
        category = "offroad",
        price = 13700,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asea",
        category = "sedans",
        price = 11600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stretch",
        category = "sedans",
        price = 18500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "blista",
        category = "compacts",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "premier",
        category = "sedans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler6",
        category = "sedans",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito4",
        category = "vans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito2",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "peyote3",
        category = "sedans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
     {
        model = "speedo2",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "blista3",
        category = "compacts",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rebel",
        category = "offroad",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rumpo",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "speedo",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "brioso2",
        category = "compacts",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "club",
        category = "compacts",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "issi3",
        category = "compacts",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "minivan",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "minivan2",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "moonbeam",
        category = "vans",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "pony",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "vivanite",
        category = "sports",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rumpo3",
        category = "vans",
        price = 15500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga2",
        category = "vans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga4",
        category = "vans",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "zion3",
        category = "sports",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "picador",
        category = "vans",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo",
        category = "sedans",
        price = 15600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbadmiral",
        category = "sedans",
        price = 17500,
        speed = 40,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "gbhades",
        category = "sports",
        price = 18500,
        speed = 40,
        acceleration = 35,
        braking = 25,
    },
{
    model = "gt500",
    category = "sports",
    price = 38500,
    speed = 55,
    acceleration = 35,
    braking = 25,
},
{
    model = "tulip",
    category = "muscle",
    price = 31500,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "issi2",
    category = "compacts",
    price = 24500,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "issi8",
    category = "sports",
    price = 45500,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "omnis",
    category = "sports",
    price = 45500,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "felon",
    category = "coupes",
    price = 28700,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "superd",
    category = "sedans",
    price = 32200,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "windsor",
    category = "coupes",
    price = 27300,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "ellie",
    category = "muscle",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 30,
},
{
    model = "voltic",
    category = "sports",
    price = 31850,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "phoenix",
    category = "muscle",
    price = 33600,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "gbstanierle",
    category = "sedans",
    price = 35000,
    speed = 45,
    acceleration = 35,
    braking = 25,
},
{
    model = "gresley",
    category = "suvs",
    price = 34300,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "surge",
    category = "sedans",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "sabregt2",
    category = "muscle",
    price = 24500,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "mamba",
    category = "sports",
    price = 24850,
    speed = 55,
    acceleration = 35,
    braking = 25,
},
{
    model = "dubsta",
    category = "suvs",
    price = 29050,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "warrener2",
    category = "sedans",
    price = 29750,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "rocoto",
    category = "suvs",
    price = 30450,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "oracle",
    category = "coupes",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "oracle2",
    category = "coupes",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "felon2",
    category = "coupes",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "feltzer2",
    category = "sports",
    price = 29750,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "fq2",
    category = "suvs",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "gauntlet3",
    category = "muscle",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "everon",
    category = "offroad",
    price = 38500,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "raiden",
    category = "sports",
    price = 38500,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "sentinel3",
    category = "coupes",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "exemplar",
    category = "coupes",
    price = 27650,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "contender",
    category = "suvs",
    price = 38500,
    speed = 57,
    acceleration = 35,
    braking = 25,
},
{
    model = "casco",
    category = "sports",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "sandking2",
    category = "offroad",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "hellion",
    category = "offroad",
    price = 34650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "huntley",
    category = "suvs",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "impaler3",
    category = "muscle",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "tailgater",
    category = "sedans",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "gbbisonstx",
    category = "vans",
    price = 34650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "aleutian",
    category = "sedans",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "faction",
    category = "muscle",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "blista2",
    category = "compacts",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "bobcatxl",
    category = "vans",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "blade",
    category = "muscle",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "baller2",
    category = "suvs",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "gbesperta",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "gbtahomagt",
    category = "sports",
    price = 70000000,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "asterope2",
    category = "sedans",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "comet4",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "jb7002",
    category = "sports",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "serrano",
    category = "suvs",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "michelli",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "retinue",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "schafter2",
    category = "sedans",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "sugoi",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "prairie",
    category = "compacts",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "futo",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "nightshade",
    category = "muscle",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "dukes",
    category = "muscle",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "fusilade",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "gbturismogts",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "cognoscenti",
    category = "sedans",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "jackal",
    category = "coupes",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "penumbra",
    category = "sports",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "kamacho",
    category = "offroad",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "monroe",
    category = "sports",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "nebula",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "stingergt",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "fugitive",
    category = "sedans",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "stalion",
    category = "muscle",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "stalion2",
    category = "muscle",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "l35",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "landstlkr2",
    category = "suvs",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "streiter",
    category = "sports",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "gbstarlight",
    category = "sports",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "tampa",
    category = "muscle",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "vamos",
    category = "muscle",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "verlierer2",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "viseris",
    category = "sports",
    price = 31920,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "sandking",
    category = "offroad",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "schafter4",
    category = "sedans",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "patriot",
    category = "suvs",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "slamvan3",
    category = "muscle",
    price = 27650,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "rapidgt3",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "retinue2",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "gbschrauber",
    category = "sports",
    price = 38500,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "zion2",
    category = "coupes",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "sabregt",
    category = "muscle",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 32,
},
{
    model = "terminus",
    category = "sedans",
    price = 24850,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "z190",
    category = "sports",
    price = 24850,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "zion",
    category = "coupes",
    price = 24850,
    speed = 30,
    acceleration = 25,
    braking = 20,
},
{
    model = "gbbriosof",
    category = "compacts",
    price = 27650,
    speed = 40,
    acceleration = 35,
    braking = 25,
},
{
    model = "gbimpaler",
    category = "muscle",
    price = 27650,
    speed = 45,
    acceleration = 45,
    braking = 25,
},
{
    model = "gbmojave",
    category = "offroad",
    price = 27650,
    speed = 306,
    acceleration = 35,
    braking = 25,
},
{
    model = "gbraidillon",
    category = "sports",
    price = 27650,
    speed = 37,
    acceleration = 35,
    braking = 20,
},
{
    model = "gbvivant",
    category = "sports",
    price = 24850,
    speed = 45,
    acceleration = 35,
    braking = 25,
},
{
    model = "cinquemila",
    category = "sedans",
    price = 227500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "clubxr",
    category = "sports",
    price = 227500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "cog55",
    category = "sedans",
    price = 227500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "cogcabrio",
    category = "coupes",
    price = 227500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "dominator8",
    category = "muscle",
    price = 290500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "comet3",
    category = "sports",
    price = 220500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbmogulrs",
    category = "sports",
    price = 459200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbsultanrsx",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "banshee",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "buffalo2",
    category = "muscle",
    price = 227500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "infernus2",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "komoda",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbcomets1t",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "coquette",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "coureur",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "dominator",
    category = "muscle",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "dominator3",
    category = "muscle",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "f620",
    category = "coupes",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "issi7",
    category = "compacts",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "jubilee",
    category = "suvs",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "kuruma",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "paragon",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "penumbra2",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "ruiner4",
    category = "muscle",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "schafter3",
    category = "sedans",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "schlagen",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "windsor2",
    category = "coupes",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "surano",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "savestra",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "turismo2",
    category = "super",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "tailgater2",
    category = "sedans",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "kanjo",
    category = "compacts",
    price = 242200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "khamelion",
    category = "coupes",
    price = 242200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "neon",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "ninef",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "omnisegt",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "furoregt",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "fr36",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "ruston",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "locust",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "lynx",
    category = "sports",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "vstr",
    category = "sedans",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "rhinehart",
    category = "sedans",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "zentorno",
    category = "super",
    price = 459200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "ruiner",
    category = "muscle",
    price = 319200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "specter2",
    category = "sports",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "rebla",
    category = "suvs",
    price = 249200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "remus",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "comet2",
    category = "sports",
    price = 396200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "adder",
    category = "super",
    price = 459200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gauntlet",
    category = "muscle",
    price = 249200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "rapidgt",
    category = "sports",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbeonn",
    category = "sports",
    price = 396200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "bestiagts",
    category = "sports",
    price = 459200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbneonct",
    category = "sports",
    price = 403200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "vigero2",
    category = "muscle",
    price = 70000000,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "novak",
    category = "suvs",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "italigto",
    category = "sports",
    price = 459200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "imorgon",
    category = "sports",
    price = 529200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "elegy2",
    category = "sports",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "cheetah2",
    category = "super",
    price = 529200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "buffalo3",
    category = "muscle",
    price = 249200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "brawler",
    category = "offroad",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "brioso",
    category = "compacts",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "baller3",
    category = "suvs",
    price = 179200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "baller4",
    category = "suvs",
    price = 249200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "baller7",
    category = "suvs",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "baller8",
    category = "suvs",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "astron",
    category = "suvs",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbdominatorgsx",
    category = "sports",
    price = 529200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "r300",
    category = "sports",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbkomodagt",
    category = "sports",
    price = 389200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbbisonhf",
    category = "offroad",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbargento7f",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "t20",
    category = "super",
    price = 599200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "pariah",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "specter",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "revolter",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "infernus",
    category = "super",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "futo2",
    category = "compacts",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "massacro",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "comet5",
    category = "sports",
    price = 312200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "buffalo4",
    category = "muscle",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "bullet",
    category = "super",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "dominator2",
    category = "muscle",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "sultan3",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "sultan2",
    category = "sports",
    price = 387800,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "jester3",
    category = "sports",
    price = 388500,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "schwarzer",
    category = "sports",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "sentinel",
    category = "coupes",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbgresleystx",
    category = "suvs",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbharmann",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbirisz",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbissimetro",
    category = "compacts",
    price = 452200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
{
    model = "gbsidewinder",
    category = "sports",
    price = 382200,
    speed = 65,
    acceleration = 56,
    braking = 46,
},
     {
        model = "entity3",
        category = "super",
        price = 650540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "emerus",
        category = "super",
        price = 650540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "buffalo5",
        category = "muscle",
        price = 750540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbprospero",
        category = "super",
        price = 1505400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbsapphire",
        category = "super",
        price = 650540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gb811s2",
        category = "super",
        price = 950540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
        {
        model = "gbcometcl",
        category = "super",
        price = 950540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
        {
        model = "gbcomets1t",
        category = "super",
        price = 1505400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbcomets2r",
        category = "sports",
        price = 1505400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbcomets2rc",
        category = "sports",
        price = 1505400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbschlagenr",
        category = "sports",
        price = 650540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
        {
        model = "gbschlagensp",
        category = "sports",
        price = 750540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "tempesta",
        category = "super",
        price = 850540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "entity2",
        category = "super",
        price = 950540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "turismo3",
        category = "super",
        price = 950540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "turismor",
        category = "super",
        price = 750540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "banshee2",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbbanshees",
        category = "super",
        price = 950540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "entityxf",
        category = "super",
        price = 850540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "sm722",
        category = "sports",
        price = 750540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "neo",
        category = "sports",
        price = 750540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "jester4",
        category = "sports",
        price = 750540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gp1",
        category = "super",
        price = 780540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "furia",
        category = "super",
        price = 650540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbtenfr",
        category = "super",
        price = 780540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "corsita",
        category = "sports",
        price = 780540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
        {
        model = "gbsentinelgts",
        category = "sports",
        price = 680540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "elegy",
        category = "sports",
        price = 680540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "comet6",
        category = "sports",
        price = 680540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "comet7",
        category = "sports",
        price = 780540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbschwartzers",
        category = "sports",
        price = 680540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbsolacev",
        category = "sports",
        price = 680540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbsolace",
        category = "sports",
        price = 780540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "growler",
        category = "sports",
        price = 1205400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "euros",
        category = "sports",
        price = 780540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbtr3s",
        category = "super",
        price = 1505400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
        {
        model = "docktug",
        category = "utility",
        price = 9500,
        speed = 75,
        acceleration = 15,
        braking = 26,
    },
    {
        model = "vigero3",
        category = "muscle",
        price = 556000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "elegyrh7",
        category = "sports",
        price = 1705400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbbanshees",
        category = "super",
        price = 880540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbmilano",
        category = "super",
        price = 1705400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbnexusrr",
        category = "super",
        price = 880540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbronin",
        category = "super",
        price = 1705400,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "cypherct",
        category = "sports",
        price = 980540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "cypher",
        category = "sports",
        price = 880540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "champion",
        category = "super",
        price = 880540,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "hakuchou",
        category = "motorcycles",
        price = 65000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "hakuchou2",
        category = "motorcycles",
        price = 75000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "ruffian",
        category = "motorcycles",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "enduro",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "esskey",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "thrust",
        category = "motorcycles",
        price = 45500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "zombiea",
        category = "motorcycles",
        price = 10000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "zombieb",
        category = "motorcycles",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "akuma",
        category = "motorcycles",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "avarus",
        category = "motorcycles",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "bagger",
        category = "motorcycles",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "bati",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "bf400",
        category = "motorcycles",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "blazer4",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "hexer",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "daemon",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "daemon2",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "defiler",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "diablous",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "diablous2",
        category = "motorcycles",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "cliffhanger",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "chimera",
        category = "motorcycles",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "sanctus",
        category = "motorcycles",
        price = 25500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "sanchez",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "sovereign",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "gargoyle",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "lectro",
        category = "motorcycles",
        price = 25500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "manchez3",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "reever",
        category = "motorcycles",
        price = 25500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "ratbike",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "manchez",
        category = "motorcycles",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "manchez2",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "faggio3",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "faggio",
        category = "motorcycles",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "nemesis",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "nightblade",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "fcr",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "fcr2",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "innovation",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "stryder",
        category = "motorcycles",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "vader",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "vindicator",
        category = "motorcycles",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "vortex",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "shinobi",
        category = "motorcycles",
        price = 65000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "blazer",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "powersurge",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "verus",
        category = "motorcycles",
        price = 65000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "wolfsbane",
        category = "motorcycles",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
}