local DEBUG_CARS <const> = {
    {
        model = "taco",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "romero",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "emperor",
        category = "sedan",
        price = 8000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tornado5",
        category = "sedan",
        price = 7000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dloader",
        category = "suv",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "broadway",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "btype2",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hermes",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "pigalle",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "clique",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "clique2",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hustler",
        category = "suv",
        price = 11000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "kalahari",
        category = "offroad",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "peyote",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stafford",
        category = "suv",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "voodoo2",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "journey",
        category = "vans",
        price = 11000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "manana2",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "postlude",
        category = "sedan",
        price = 6500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "surfer",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "voodoo",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "washington",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "weevil",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tornado",
        category = "sedan",
        price = 7850,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tahoma",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "glendale2",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "fagaloa",
        category = "suv",
        price = 10560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "lurcher",
        category = "sedan",
        price = 8560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
     {
        model = "dynasty",
        category = "sedan",
        price = 7850,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "regina",
        category = "sedan",
        price = 8540,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "glendale",
        category = "sedan",
        price = 7560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "warrener",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "patriot",
        category = "suv",
        price = 12000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "kanjosj",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "manana",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler5",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dukes3",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "eudora",
        category = "sedan",
        price = 6500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rancherxl",
        category = "suv",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "issi6",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "caddy2",
        category = "utility",
        price = 5600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "camper",
        category = "vans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "boxville",
        category = "vans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck3",
        category = "utility",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck2",
        category = "utility",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck4",
        category = "utility",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule3",
        category = "vans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule4",
        category = "vans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "primo",
        category = "sedan",
        price = 13000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rhapsody1",
        category = "sedan",
        price = 12000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "seminole",
        category = "suv",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo2",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "monstrociti",
        category = "suv",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "coquette2",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "coquette3",
        category = "sports",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "chino",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "chino2",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asbo",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bifta",
        category = "offroad",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bison",
        category = "utility",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bodhi2",
        category = "utility",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "boor",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dilettante",
        category = "sedan",
        price = 12300,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "primo2",
        category = "sedan",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stinger",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stanier",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "slamvan2",
        category = "utility",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tulip2",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hotknife",
        category = "sports",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo3",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
        {
        model = "granger",
        category = "suv",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "greenwood",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "ztype",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mesa",
        category = "offroad",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "slamvan",
        category = "utility",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "seminole2",
        category = "suv",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "landstalker",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "radi",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "habanero",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mesa3",
        category = "offroad",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "emperor2",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "faction2",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "btype3",
        category = "sedan",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bjxl",
        category = "suv",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbvivant",
        category = "sports",
        price = 15500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "baller",
        category = "suv",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asterope",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "panto",
        category = "compact",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "ingot",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "lguard",
        category = "suv",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "winky",
        category = "offroad",
        price = 13700,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asea",
        category = "sedan",
        price = 11600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stretch",
        category = "sedan",
        price = 18500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "blista",
        category = "compact",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "premier",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler6",
        category = "sedan",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito4",
        category = "vans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito2",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "peyote3",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
     {
        model = "speedo2",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "blista3",
        category = "compact",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rebel",
        category = "offroad",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rumpo",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "speedo",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "brioso2",
        category = "compact",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "club",
        category = "compact",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "issi3",
        category = "compact",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "minivan",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "minivan2",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "moonbeam",
        category = "vans",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "pony",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "toreador",
        category = "sports",
        price = 17500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "vivanite",
        category = "sports",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rumpo3",
        category = "vans",
        price = 15500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga2",
        category = "vans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga4",
        category = "vans",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "zion3",
        category = "sports",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "patriot3",
        category = "suv",
        price = 18500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "picador",
        category = "utility",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo",
        category = "sedan",
        price = 15600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbadmiral",
        category = "sedan",
        price = 17500,
        speed = 40,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "gbhades",
        category = "sports",
        price = 18500,
        speed = 40,
        acceleration = 35,
        braking = 25,
    },




}
