Config.Vehicles = {
   {
        model = "taco",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "romero",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "emperor",
        category = "sedan",
        price = 8000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tornado5",
        category = "sedan",
        price = 7000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dloader",
        category = "suv",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "broadway",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "btype2",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hermes",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "pigalle",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "clique",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "clique2",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hustler",
        category = "suv",
        price = 11000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "kalahari",
        category = "offroad",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "peyote",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stafford",
        category = "suv",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "voodoo2",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "journey",
        category = "vans",
        price = 11000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "manana2",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "postlude",
        category = "sedan",
        price = 6500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "surfer",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "voodoo",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "washington",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "weevil",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tornado",
        category = "sedan",
        price = 7850,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tahoma",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "glendale2",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "fagaloa",
        category = "suv",
        price = 10560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "lurcher",
        category = "sedan",
        price = 8560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
     {
        model = "dynasty",
        category = "sedan",
        price = 7850,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "regina",
        category = "sedan",
        price = 8540,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "glendale",
        category = "sedan",
        price = 7560,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "warrener",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "patriot",
        category = "suv",
        price = 12000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "kanjosj",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "manana",
        category = "sedan",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler5",
        category = "sedan",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dukes3",
        category = "sedan",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "eudora",
        category = "sedan",
        price = 6500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rancherxl",
        category = "suv",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "issi6",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "caddy2",
        category = "utility",
        price = 5600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "camper",
        category = "vans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "boxville",
        category = "vans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck3",
        category = "utility",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck2",
        category = "utility",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "towtruck4",
        category = "utility",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule",
        category = "vans",
        price = 7500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule3",
        category = "vans",
        price = 8500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mule4",
        category = "vans",
        price = 9500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "primo",
        category = "sedan",
        price = 13000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rhapsody1",
        category = "sedan",
        price = 12000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "seminole",
        category = "suv",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo2",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "monstrociti",
        category = "suv",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "coquette2",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "coquette3",
        category = "sports",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "chino",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "chino2",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asbo",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bifta",
        category = "offroad",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bison",
        category = "utility",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bodhi2",
        category = "utility",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "boor",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "dilettante",
        category = "sedan",
        price = 12300,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "primo2",
        category = "sedan",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stinger",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stanier",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "slamvan2",
        category = "utility",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "tulip2",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "hotknife",
        category = "sports",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo3",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
        {
        model = "granger",
        category = "suv",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "greenwood",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "ztype",
        category = "sports",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mesa",
        category = "offroad",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "slamvan",
        category = "utility",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "seminole2",
        category = "suv",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "landstalker",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "radi",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "habanero",
        category = "suv",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mesa3",
        category = "offroad",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "emperor2",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "faction2",
        category = "sedan",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "btype3",
        category = "sedan",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "bjxl",
        category = "suv",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbvivant",
        category = "sports",
        price = 15500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "baller",
        category = "suv",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asterope",
        category = "sedan",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "panto",
        category = "compact",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "ingot",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "lguard",
        category = "suv",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "winky",
        category = "offroad",
        price = 13700,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "asea",
        category = "sedan",
        price = 11600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "stretch",
        category = "sedan",
        price = 18500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "blista",
        category = "compact",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "premier",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "impaler6",
        category = "sedan",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito4",
        category = "vans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "burrito2",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "peyote3",
        category = "sedan",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
     {
        model = "speedo2",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "blista3",
        category = "compact",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rebel",
        category = "offroad",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rumpo",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "speedo",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "brioso2",
        category = "compact",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "club",
        category = "compact",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "issi3",
        category = "compact",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "minivan",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "minivan2",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "moonbeam",
        category = "vans",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "pony",
        category = "vans",
        price = 10500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "vivanite",
        category = "sports",
        price = 16500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rumpo3",
        category = "vans",
        price = 15500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga",
        category = "vans",
        price = 11500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga2",
        category = "vans",
        price = 12500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "youga4",
        category = "vans",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "zion3",
        category = "sports",
        price = 13500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "patriot3",
        category = "suv",
        price = 18500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "picador",
        category = "utility",
        price = 14500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "virgo",
        category = "sedan",
        price = 15600,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbadmiral",
        category = "sedan",
        price = 17500,
        speed = 40,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "gbhades",
        category = "sports",
        price = 18500,
        speed = 40,
        acceleration = 35,
        braking = 25,
    },
        {
        model = "gt500",
        category = "sports",
        price = 55000,
        speed = 55,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "tulip",
        category = "muscle",
        price = 45000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "issi2",
        category = "compact",
        price = 35000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "issi8",
        category = "sports",
        price = 65000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "omnis",
        category = "sports",
        price = 65000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "felon",
        category = "coupe",
        price = 41000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "superd",
        category = "sedan",
        price = 46000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "windsor",
        category = "coupe",
        price = 39000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "ellie",
        category = "muscle",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 30,
    },
    {
        model = "voltic",
        category = "sports",
        price = 45500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "phoenix",
        category = "muscle",
        price = 48000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbstanierle",
        category = "sedan",
        price = 50000,
        speed = 45,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "gresley",
        category = "suv",
        price = 49000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "surge",
        category = "sedan",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "sabregt2",
        category = "muscle",
        price = 35000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "mamba",
        category = "sports",
        price = 35500,
        speed = 55,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "dubsta",
        category = "suv",
        price = 41500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "warrener2",
        category = "sedan",
        price = 42500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "rocoto",
        category = "suv",
        price = 43500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "oracle",
        category = "coupe",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "oracle2",
        category = "coupe",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "felon2",
        category = "coupe",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "feltzer2",
        category = "sports",
        price = 42500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "fq2",
        category = "suv",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gauntlet3",
        category = "muscle",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "everon",
        category = "offroad",
        price = 55000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "raiden",
        category = "sports",
        price = 55000,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "sentinel3",
        category = "coupe",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "exemplar",
        category = "coupe",
        price = 39500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "contender",
        category = "suv",
        price = 55000,
        speed = 57,
        acceleration = 35,
        braking = 25,
    },
        {
        model = "casco",
        category = "sports",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "sandking2",
        category = "offroad",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "hellion",
        category = "offroad",
        price = 49500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "huntley",
        category = "suv",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "impaler3",
        category = "muscle",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "tailgater",
        category = "sedan",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "gbbisonstx",
        category = "utility",
        price = 49500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "aleutian",
        category = "sedan",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "faction",
        category = "muscle",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "buccanee2",
        category = "muscle",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "briosof",
        category = "compact",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "blista2",
        category = "compact",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "bobcatxl",
        category = "utility",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "blade",
        category = "muscle",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "baller2",
        category = "suv",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "gbesperta",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "gbtahgt",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "asterope2",
        category = "sedan",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "comet4",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "jb7002",
        category = "sports",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "serrano",
        category = "suv",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "michelli",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "retinue",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "schafter2",
        category = "sedan",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "sugoi",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "prairie",
        category = "compact",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "futo",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "nightshade",
        category = "muscle",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "dukes",
        category = "muscle",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "fusilade",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "gbturgts",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "cognosc",
        category = "sedan",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "cometcl",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "jackal",
        category = "coupe",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
        {
        model = "penumbra",
        category = "sports",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "kamacho",
        category = "offroad",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "monroe",
        category = "sports",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "nebula",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "stingergt",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "fugitive",
        category = "sedan",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "stalion",
        category = "muscle",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "stalion2",
        category = "muscle",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "l35",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "landstlkr2",
        category = "suv",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "streiter",
        category = "sports",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "gbstarlght",
        category = "sports",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "tampa",
        category = "muscle",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "vamos",
        category = "muscle",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "verlierer2",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "viseris",
        category = "sports",
        price = 45600,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "sandking",
        category = "offroad",
        price = 39500,
         speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "schafter4",
        category = "sedan",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "patriot",
        category = "suv",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "slamvan3",
        category = "muscle",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "rapidgt3",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "retinue2",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "gbschrauber",
        category = "sports",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "zion2",
        category = "coupe",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "sabregt",
        category = "muscle",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "trophytrunk",
        category = "offroad",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
    {
        model = "trophytrunbk2",
        category = "offroad",
        price = 39500,
        speed = 45,
        acceleration = 35,
        braking = 32,
    },
        {
        model = "terminus",
        category = "sedan",
        price = 35500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "z190",
        category = "sports",
        price = 35500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "zion",
        category = "coupe",
        price = 35500,
        speed = 30,
        acceleration = 25,
        braking = 20,
    },
    {
        model = "gbbriosof",
        category = "compact",
        price = 39500,
        speed = 40,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "gbimpaler",
        category = "muscle",
        price = 39500,
        speed = 45,
        acceleration = 45,
        braking = 25,
    },
    {
        model = "gbmojave",
        category = "offroad",
        price = 39500,
        speed = 306,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "gbraidillon",
        category = "sports",
        price = 39500,
        speed = 37,
        acceleration = 35,
        braking = 20,
    },
    {
        model = "gbturgt",
        category = "sports",
        price = 35500,
        speed = 39,
        acceleration = 35,
        braking = 25,
    },
    {
        model = "gbvivant",
        category = "sports",
        price = 35500,
        speed = 45,
        acceleration = 35,
        braking = 25,
    },
        {
        model = "cinquemila",
        category = "sedan",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "clubxr",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "cog55",
        category = "sedan",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "cogcabrio",
        category = "coupe",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "dominator8",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "comet3",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbmogulrs",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbsultrsx",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "banshee",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "buffalo2",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "infernus2",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "komoda",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "comets1t",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "coquette",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "coureur",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "dominator",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "dominator3",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "f620",
        category = "coupe",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "issi7",
        category = "compact",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "jubilee",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "kuruma",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "paragon",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "penumbra2",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "ruiner4",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "schafter3",
        category = "sedan",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "schlagen",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
        {
        model = "windsor2",
        category = "coupe",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "surano",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "savestra",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "turismo2",
        category = "super",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "tailgater2",
        category = "sedan",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "kanjo",
        category = "compact",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "khamel",
        category = "coupe",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "neon",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "ninef",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "omnisegt",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "furoregt",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "fr36",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "ruston",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "locust",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "lynx",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "vstr",
        category = "sedan",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "rhinehart",
        category = "sedan",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "zentorno",
        category = "super",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "ruiner",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "specter2",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "rebla",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "remus",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "comet2",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "adder",
        category = "super",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
        {
        model = "gauntlet",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "rapidgt",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbeon",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "bestiagts",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbneonct",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "vigero2",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "novak",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "italigto",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "imorgon",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "elegy2",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "cheetah2",
        category = "super",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "buffalo3",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "brawler",
        category = "offroad",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "brioso",
        category = "compact",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "baller3",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "baller4",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "baller7",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "baller8",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "astron",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbdomgsx",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "r300",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbkomodagt",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbbisonhf",
        category = "offroad",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbargento7f",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
        {
        model = "t20",
        category = "super",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "pariah",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "specter",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "revolter",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "infernus",
        category = "super",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "futo2",
        category = "compact",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "massacro",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "comet5",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "buffalo4",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "bullet",
        category = "super",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "dominator2",
        category = "muscle",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "sultan3",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "sultan2",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "jester",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "jester3",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "schwarzer",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "sentinel",
        category = "coupe",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbgresleystx",
        category = "suv",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbharmenn",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbirisz",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbissimetro",
        category = "compact",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
    {
        model = "gbsidewinder",
        category = "sports",
        price = 5000000,
        speed = 65,
        acceleration = 56,
        braking = 46,
    },
        {
        model = "entity3",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "emerus",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "buffalo5",
        category = "muscle",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "ardent",
        category = "sportsclassic",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbprospero",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbsapphire",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gb811s2",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbcomets2r",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbcomets2rc",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbschlagenr",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "tempesta",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "entity2",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "turismo3",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "turismor",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "banshee2",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "banshees",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "entityxf",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "sm722",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "neo",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "jester4",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gp1",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "furia",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbtenfr",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "corsita",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
        {
        model = "gbsentinelgts",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "elegy",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "comet6",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "comet7",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbschwarz",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbsolace",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "growler",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "euros",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "solacev",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "schlagensp",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbtr3s",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "vigero3",
        category = "muscle",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "elegryrh7",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbbanshee",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbmilano",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbnexusrr",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "gbronin",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "cypherct",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "cypher",
        category = "sports",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "champion",
        category = "super",
        price = 10000000,
        speed = 75,
        acceleration = 76,
        braking = 56,
    },
    {
        model = "hakuchou",
        category = "motorcycle",
        price = 65000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "hakuchou2",
        category = "motorcycle",
        price = 75000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "ruffian",
        category = "motorcycle",
        price = 55000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "enduro",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "esskey",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "thrust",
        category = "motorcycle",
        price = 45500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "zombiea",
        category = "motorcycle",
        price = 10000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "zombieb",
        category = "motorcycle",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "akuma",
        category = "motorcycle",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "avarus",
        category = "motorcycle",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "bagger",
        category = "motorcycle",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "bati",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "bf400",
        category = "motorcycle",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "blazer4",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "blazer5",
        category = "motorcycle",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "hexer",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "daemon",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "daemon2",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "defiler",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "diablous",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "diablous2",
        category = "motorcycle",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "cliffhang",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "chimera",
        category = "motorcycle",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "sanctus",
        category = "motorcycle",
        price = 25500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "sanchez",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "sovereign",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "gargoyle",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "lectro",
        category = "motorcycle",
        price = 25500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "manchez3",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "reever",
        category = "motorcycle",
        price = 25500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "ratbike",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "manchez",
        category = "motorcycle",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "manchez2",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "faggio3",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "faggio",
        category = "motorcycle",
        price = 7500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "nemesis",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "nightblade",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "fcr",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "fcr2",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "innovat",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "stryder",
        category = "motorcycle",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "vader",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "vindicator",
        category = "motorcycle",
        price = 35000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "vortex",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "shinobi",
        category = "motorcycle",
        price = 65000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "blazer",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "powersurge",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "verus",
        category = "motorcycle",
        price = 65000,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
    {
        model = "wolfsbane",
        category = "motorcycle",
        price = 12500,
        speed = 45,
        acceleration = 35,
        braking = 40,
    },
}
